version: "3"
services:
  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ~/xkdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:4.16
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_LISTEN_PORT=$PGADMIN_LISTEN_PORT
    links:
      - pg
    ports:
      - 2345:$PGADMIN_LISTEN_PORT
  nginx:
    image: nginx:1.17.6
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 444:444
    links:
      - pgadmin
      - xk
  xk:
    image: golang:1.13.5
    volumes:
      - .:/usr/src/app
    command:
      - /bin/bash
      - -c
      - |
        ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        cd /usr/src/app
        go run main.go
    environment: 
      - GIN_MODE=release
      - GOPROXY=https://goproxy.io
      - GO111MODULE=on
      - PORT=80
    links: 
      - pg
    ports:
      - 80:80